apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-webapp
  template:
    metadata:
      labels:
        app: nodejs-webapp
    spec:
      containers:
      - name: nodejs-webapp-container
        image: ojosamuel/nodejs-webapp
        ports:
        - containerPort: 80
       
